version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    versioning-strategy: lockfile-only
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 10
    rebase-strategy: 'disabled'
